language: python

sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

addons:
    apt:
        packages:
            - mongodb

dist: xenial

script:
    - sudo systemctl start mongodb.service
    - make pytest
